project_id = "zulnuayumxsdbivigvfe"

[functions.process-email-queue]
verify_jwt = true

[functions.activity-tracker]
verify_jwt = false

[functions.cron-sync-staff]
verify_jwt = false

[functions.public-sessions]
verify_jwt = false

[functions.translate-batch]
verify_jwt = false

[functions.roblox-avatar]
verify_jwt = false
